version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    entrypoint: /usr/bin/entrypoint.sh
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/babbler_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: babbler_development
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      CABLE_URL: ws://action-cable:28080
    depends_on:
      - db
      - redis
      - action-cable

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: babbler_development

  redis:
    image: redis:7
    command: ["redis-server"]
    networks:
      - default

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/babbler_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  action-cable:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0 -p 28080
    entrypoint: /usr/bin/entrypoint.sh
    volumes:
      - .:/rails
    ports:
      - "28080:28080"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/babbler_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
