version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    entrypoint: /usr/bin/entrypoint.sh
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: babbler_development

  redis:
    image: redis:7
    command: ["redis-server"]
    networks:
      - default
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: