name: Babbler CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.2.2]

    services:
      postgres:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: babbler_test
      redis:
        image: redis:7
        ports:
          - "6379:6379"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: babbler_test
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432

      - name: Log PostgreSQL status
        run: pg_isready -h 127.0.0.1 -p 5432 -U postgres

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: babbler_test
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432

      - name: Wait for Redis to be ready
        run: |
          until redis-cli -h 127.0.0.1 -p 6379 ping; do
            echo "Waiting for Redis..."
            sleep 3
          done

        env:
          REDIS_URL: redis://127.0.0.1:6379/1

      - name: Log Redis status
        run: redis-cli -h 127.0.0.1 -p 6379 ping

        env:
          REDIS_URL: redis://127.0.0.1:6379/1

      - name: Set up database
        run: |
          bundle exec rails db:prepare

        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/babbler_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: babbler_test
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432

      - name: Run tests
        run: bundle exec rspec

        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/babbler_test
          REDIS_URL: redis://127.0.0.1:6379/1
